version: '2'

services:
  homestead:
    image: laraedit/laraedit
    container_name: tua_homestead
    working_dir: /var/www/html/app
    volumes:
      - .:/var/www/html/app
      - data:/var/lib/mysql
    ports:
      - "8080:80"
      - "33066:3306"
volumes:
  data: